import { defineStore } from "pinia";

export const useCardsStore = defineStore("cards", {
  state: () => {
    return {
      cards: [
        { cardPath: "clubs_2", value: 2 },
        { cardPath: "clubs_3", value: 3 },
        { cardPath: "clubs_4", value: 4 },
        { cardPath: "clubs_5", value: 5 },
        { cardPath: "clubs_6", value: 6 },
        { cardPath: "clubs_7", value: 7 },
        { cardPath: "clubs_8", value: 8 },
        { cardPath: "clubs_9", value: 9 },
        { cardPath: "clubs_10", value: 10 },
        { cardPath: "clubs_jack", value: 10 },
        { cardPath: "clubs_queen", value: 10 },
        { cardPath: "clubs_king", value: 10 },
        { cardPath: "clubs_ace", value: 11 },
        { cardPath: "diamonds_2", value: 2 },
        { cardPath: "diamonds_3", value: 3 },
        { cardPath: "diamonds_4", value: 4 },
        { cardPath: "diamonds_5", value: 5 },
        { cardPath: "diamonds_6", value: 6 },
        { cardPath: "diamonds_7", value: 7 },
        { cardPath: "diamonds_8", value: 8 },
        { cardPath: "diamonds_9", value: 9 },
        { cardPath: "diamonds_10", value: 10 },
        { cardPath: "diamonds_jack", value: 10 },
        { cardPath: "diamonds_queen", value: 10 },
        { cardPath: "diamonds_king", value: 10 },
        { cardPath: "diamonds_ace", value: 11 },
        { cardPath: "hearts_2", value: 2 },
        { cardPath: "hearts_3", value: 3 },
        { cardPath: "hearts_4", value: 4 },
        { cardPath: "hearts_5", value: 5 },
        { cardPath: "hearts_6", value: 6 },
        { cardPath: "hearts_7", value: 7 },
        { cardPath: "hearts_8", value: 8 },
        { cardPath: "hearts_9", value: 9 },
        { cardPath: "hearts_10", value: 10 },
        { cardPath: "hearts_jack", value: 10 },
        { cardPath: "hearts_queen", value: 10 },
        { cardPath: "hearts_king", value: 10 },
        { cardPath: "hearts_ace", value: 11 },
        { cardPath: "spades_2", value: 2 },
        { cardPath: "spades_3", value: 3 },
        { cardPath: "spades_4", value: 4 },
        { cardPath: "spades_5", value: 5 },
        { cardPath: "spades_6", value: 6 },
        { cardPath: "spades_7", value: 7 },
        { cardPath: "spades_8", value: 8 },
        { cardPath: "spades_9", value: 9 },
        { cardPath: "spades_10", value: 10 },
        { cardPath: "spades_jack", value: 10 },
        { cardPath: "spades_queen", value: 10 },
        { cardPath: "spades_king", value: 10 },
        { cardPath: "spades_ace", value: 11 },
      ],
    };
  },
});
